### ISSUE TITLE
Initialize error on project without version control

### ISSUE THREAD

**Issue by anmonteiro** [freebroccolo/ocaml-language-server#58] opened 2017-11-11 22:12 UTC
I'm getting the following stacktrace in stderr when opening a file in a workspace that's not VC-backed:

```
/usr/local/lib/node_modules/ocaml-language-server/bin/server/processes/merlin.js:29
                throw error;
                ^

Error: spawn ocamlmerlin ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Process lsp-ocaml stderr finished
```

related to https://github.com/emacs-lsp/lsp-mode/issues/152

**Comment by freebroccolo** [comment] 2017-11-11 22:32
This error (`spawn ocamlmerlin ENOENT`) means that when node tried to spawn `ocamlmerlin` as a child process, the binary was not found (e.g., not in your `PATH`).

The reason this is happening may be due to the fact that the `opam` environment has not already been initialized (via `~/.profile`) before the editor is started, or under the environment which it starts `ocaml-language-server`.

If this is the case, you can try starting `emacs` the terminal (make sure `ocamlmerlin` is in your `PATH` first). If that doesn't help, you may need to modify `lsp-mode` to launch `ocaml-language-server` from within a login shell (e.g., `bash -cl ...`).

I am looking at ways to work around this and have the server ensure that the environment is initialized anyway but it's a little bit tricky to do that in a clean way.

**Comment by anmonteiro** [comment] 2017-11-11 22:44
I'm quite certain that `ocamlmerlin` is in my path. Within the same editor, I only get this error when my project isn't under version control. I believe @Denommus had the same problem too.

**Comment by freebroccolo** [comment] 2017-11-11 22:48
There's no logic in the language server itself that would cause it to behave differently whether or not it is launched a project directory with version control. So that part of it would have to be something specific to emacs or `lsp-mode`. Maybe projectile has an effect on this somehow?

The only thing I know for sure is that that error is caused by `spawn` not being able to find the `ocamlmerlin` binary when it tries to launch it.

How are you starting emacs?

**Comment by anmonteiro** [comment] 2017-11-11 22:50
I see. I'm starting emacs normally through the UI but I have `exec-path-from-shell`

**Comment by freebroccolo** [comment] 2017-11-11 22:56
Yeah, that may not be enough. Under Linux, if I launch VS Code through the UI I have the same problem. But if I start it via `code` from the terminal, it works. The problem is due to when then `opam` environment is actually initialized and unfortunately this is beyond the control of the language server.

**Comment by freebroccolo** [comment] 2017-11-11 23:02
To add some further context, it is possible to get `spawn` to run a command in a shell on the server side, but there's no option to run it in a login shell specifically (so the `opam` init stuff usually won't happen). Using `exec` works for this, but unfortunately that causes communication with `ocamlmerlin` to fail due to the buffering.

**Comment by freebroccolo** [comment] 2017-11-12 01:29
Also see [this comment](https://github.com/ocaml/opam/blob/master/src/core/opamStd.ml#L725-L729). What is probably the right thing to do here is for opam to start modifying `~/.bashrc` instead of `~/.profile`.

**Comment by freebroccolo** [comment] 2017-11-12 11:00
I've made some changes which should hopefully fix the error if it's related to the login shell issue. I'll go ahead and close this. Let me know if it's still a problem.

**Comment by anmonteiro** [comment] 2017-11-12 19:53
I didn't have time to investigate your other suggestions but I wanted to report that I'm still seeing this issue on 1.0.11.

**Comment by freebroccolo** [comment] 2017-11-12 21:53
Can you give me more information about your development environment?

- what OS?
- what is the default user shell?
- where is opam initialized? (e.g., `~/.profile`, `~/.bashrc`, etc.)
- does it make a difference whether you launch the editor from the terminal?

**Comment by anmonteiro** [comment] 2017-11-12 22:20
> what OS?

macOS 10.13.1
> what is the default user shell?

ZSH

> where is opam initialized? (e.g., ~/.profile, ~/.bashrc, etc.)

`~/.zshrc`

> where is ocamlmerlin installed? (which ocamlmerlin output)

`/Users/anmonteiro/.opam/4.05.0/bin/ocamlmerlin`

> does it make a difference whether you launch the editor from the terminal?

No.

**Comment by freebroccolo** [comment] 2017-11-12 22:34
Weird. I really don't know why node spawn would be failing to find `ocamlmerlin` in that case.

If it indeed only happens when there's no version control, there has to be something else interfering with the environment because it just doesn't make sense why that would even matter.

Is it possible you have some custom configuration or plugin for zsh that could be modifying the environment in some way depending on whether or not there's version control?

I will try to reproduce this when I get a chance but can you also try changing the default shell to `bash` and having the opam initialization in `~/.profile` and seeing if that works?

There is another way I can try to launch merlin that may be more resilient but it will require refactoring certain parts of the server. I will investigate but it will probably not happen right away.

**Comment by anmonteiro** [comment] 2017-11-12 22:41
So, here's something even more weird.
The stderr process now has the following stacktrace:

```
/usr/local/lib/node_modules/ocaml-language-server/bin/server/processes/merlin.js:35
                throw error;
                ^

Error: spawn /bin/zsh ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

**Comment by freebroccolo** [comment] 2017-11-12 22:45
I see… so it looks when node tries to spawn`/bin/zsh -lc "ocamlmerlin"` even the `/bin/zsh` part is failing. I'm not sure how that's even possible.

**Comment by freebroccolo** [comment] 2017-11-14 02:22
I just tested and am able to reproduce this on my macOS system:

```
/usr/local/lib/node_modules/ocaml-language-server/bin/server/processes/merlin.js:35
                throw error;
                ^

Error: spawn /usr/local/bin/zsh ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Process lsp-ocaml stderr finished
```

I don't know what is causing this but it has to be something specifically with the Emacs LSP setup because it is the only time I have seen the spawn call fail this way.

**Comment by mickaelistria** [comment] 2018-05-24 13:05
I'm working on making a Docker image for ocaml-language-server to use in the Eclipse IDE and Eclipse Che.

Here is the Dockerfile (it's not optimized, but it has what it needs to try things)
```Dockerfile
FROM fedora:27
RUN dnf install -y bash redhat-rpm-config patch unzip which m4 ocaml opam npm
RUN opam init -y && opam install -y merlin
RUN npm install -g ocaml-language-server
ENV PATH="${PATH}:/root/.opam/default/bin"
ENTRYPOINT [ "ocaml-language-server" ]
CMD [ "--stdio" ]
```
I've built the image locally and called it `caml-language-server`

Starting the image with `docker run -i caml-language-server`, I face the error `spawn ocamlmerlin ENOENT` whenever trying to start the LS.
Now, if I mount my home folder in the docker image and start it with `docker run -v /home/mistria:/home/mistria -i caml-language-server`, I don't see this error.

It seems to me that the strategy to locate ocamlmerlin seems to depend a lot on some local filesystem specificities which are not expected to have effect on PATH resolution.

**Comment by mickaelistria** [comment] 2018-05-24 13:50
My former comment is also the reason while I opened #122 earlier. Both #122 and this #58 probably share the same root cause and take advantage of the same fix.

**Comment by shoorlyne** [comment] 2018-08-06 13:37
I am seeing this issue as well. It's blocking ...

**Comment by freebroccolo** [comment] 2018-08-06 20:29
I've responded to #122 directly.

I don't think #122 is directly related to this issue so I'm going to close this one to avoid confusion. @shoorlyne can you please create a new issue with a description of what exactly is going wrong for you (along with details about your development environment)?

**Closed by freebroccolo** 2018-08-06 20:29 UTC
Labels: A-client, A-initialization, I-crash, S-investigating
