### ISSUE TITLE
ocamlmerlin Sys_error("Broken pipe") errors on fresh projects

### ISSUE THREAD

**Issue by jchavarri** [freebroccolo/ocaml-language-server#76] opened 2017-12-03 18:13 UTC
Not sure if it's related to the recent changes An error `ocamlmerlin error: Fatal error: exception Sys_error("Broken pipe")` appears every time I save a file.

I also noticed there's the blue loading indicator on the left panel continuously active (visible on the gif below as well). 

There's been other reports on Discord:

> vscode's `CodeHelper` process has been eating 100% CPU pretty consistently

It might not be the case, but all these seem related.

![ocamlmerlin](https://user-images.githubusercontent.com/220424/33528249-bae79b02-d85d-11e7-813e-750f17364e97.gif)

**Comment by freebroccolo** [comment] 2017-12-03 19:11
Can you try installing the previous version of the extension and see if it shows the same behavior?

Also can you try ensuring that the HTML tab in your example is closed and see if it still happens when you save an OCaml or Reason file?

How many merlin files do you have in the project source tree?

It might have something to do with the new merlin auto-restart feature but I’m not sure.

**Comment by jchavarri** [comment] 2017-12-03 20:58
Thanks @freebroccolo, the latest version 1.0.16 with the auto-restart feature disabled fixed it.

> Also can you try ensuring that the HTML tab in your example is closed and see if it still happens when you save an OCaml or Reason file?

I'm pretty sure it happened with the HTML tab closed as well. Will try to go back and repro (having problems running the project in a dev environment after the latest changes).

> How many merlin files do you have in the project source tree?

You mean `.merlin`? Just this:

```
####{BSB GENERATED: NO EDIT
B lib/bs
FLG -open ReactTemplate
FLG -ppx '/Users/javi/.nvm/versions/node/v6.9.4/lib/node_modules/bs-platform/lib/reactjs_jsx_ppx_2.exe'
FLG -ppx /Users/javi/.nvm/versions/node/v6.9.4/lib/node_modules/bs-platform/lib/bsppx.exe
S /Users/javi/Development/sandbox/sauvage/node_modules/bs-platform/lib/ocaml
B /Users/javi/Development/sandbox/sauvage/node_modules/bs-platform/lib/ocaml
FLG -nostdlib -no-alias-deps -color always
FLG -w -30-40+6+7+27+32..39+44+45+101
S /Users/javi/Development/sandbox/sauvage/node_modules/reason-react/lib/ocaml
B /Users/javi/Development/sandbox/sauvage/node_modules/reason-react/lib/ocaml
S src
B lib/bs/src
####BSB GENERATED: NO EDIT}
```

**Comment by jchavarri** [comment] 2017-12-03 21:41
@freebroccolo  I can confirm the html file has no effect in the error.

There's something I find strange in `restartMerlin`. If I add a log next to [`await session.merlin.restart();`](https://github.com/jchavarri/ocaml-language-server/blob/master/src/bin/server/command/restartMerlin.ts#L5) it seems to be called roughly twice per second, without saving the file or actually doing anything, just opening vscode. Tracking it backwards, it seems to be the [`.merlin` watch handler](https://github.com/jchavarri/ocaml-language-server/blob/master/src/bin/server/feature/didChangeWatchedFiles.ts#L19-L21).

Is that expected?

**Comment by jchavarri** [comment] 2017-12-03 21:52
Removing `bsb` stops the race condition, so I guess it's like you said in Discord: `bsb` updates `.merlin` and then it modifies the file, which makes `bsb` re-run again, etc, etc.

**Comment by jchavarri** [comment] 2017-12-03 22:29
More findings. It seems the conflictive `.merlin` file is not the one in the project root, but the one found in `node_modules/reason-react`, this is the path as seen in `didChangeWatchedFiles`:
```
{ root: '/',
  dir: '/Users/javi/Development/sandbox/sauvage/node_modules/reason-react',
  base: '.merlin',
  ext: '',
  name: '.merlin' }
```

Maybe we could avoid the problem by only restarting merlin if the file is not in `node_modules`?

**Comment by freebroccolo** [comment] 2017-12-03 22:38
Thanks for investigating this.

> Removing bsb stops the race condition, so I guess it's like you said in Discord: bsb updates .merlin and then it modifies the file, which makes bsb re-run again, etc, etc.

Okay, so it sounds like one thing we need to do is when refreshing with the analyzer after a `.merlin` change, make sure not to call `bsb` again in `refreshWithKind`. This will require some refactoring.

> Maybe we could avoid the problem by only restarting merlin if the file is not in node_modules?

I'm not sure if it would solve the problem entirely but it's certainly a good idea and we should do that.

**Comment by jchavarri** [comment] 2017-12-03 23:27
> Okay, so it sounds like one thing we need to do is when refreshing with the analyzer after a `.merlin` change is make sure not to call `bsb` again in `refreshWithKind`. This will require some refactoring.

I think there might be a simpler solution: don't call `analyzer.refreshImmediate` if  `diagnostics.tools` includes `bsb`. In that case, merlin will re-analyze as soon as the user edits some file, `refreshImmediate` will run `bsb` after `.merlin` file is saved, like with any other file.

I will open a PR.

**Comment by freebroccolo** [comment] 2017-12-03 23:42
OK, that sounds like a simpler solution. I'll go ahead and merge it and close this.

**Closed by freebroccolo** 2017-12-03 23:42 UTC
Labels: A-tooling, E-medium, I-crash, I-overhead, P-high, S-investigating

**Comment by alexfedoseev** [comment] 2018-03-08 01:24
@freebroccolo @jchavarri FYI I see this error quite often in Atom. Things get worser due to Atom’s language client has limit of server restarts (5 times per 3 minutes max). And I often reach this limit so I need to reload the whole thing to get my toolchain back.

**Comment by jchavarri** [comment] 2018-03-08 09:53
@alexfedoseev What config do you have in `diagnostics.tools`? Could you confirm if it happens with both `['bsb', 'merlin']` and also just `['merlin']` only?

**Comment by alexfedoseev** [comment] 2018-03-08 16:16
@jchavarri It’s `bsb` only. I’ll check other two cases tomorrow 👍

**Comment by alexfedoseev** [comment] 2018-03-09 04:24
@jchavarri @freebroccolo 

Happens with `['bsb', 'merlin']`.
It seems w/ `['merlin']` only it doesn't happen (or happens not that often so I can't reproduce it quick).

Also, I see this in console (https://cl.ly/q3Yx) in all cases (even w/ `['merlin']` only).

BTW `merlin` errors are reported w/ `info` label in Atom b/c `bs` errors are reported w/ `severity: 1` and `merlin` errors doesn't have this property at all. Is this intentional?

**Comment by jchavarri** [comment] 2018-03-12 00:07
@alexfedoseev It could be the same problem that caused this PR was trying to solve.

It would be great if you could get some logs of what messages are sent / received just before and after the broken pipe error, and also adding the timestamps in the console. Trying to understand what's going on (i haven't been able to setup Atom in debug mode)

![image](https://user-images.githubusercontent.com/220424/37260275-8513e23e-2591-11e8-8843-265645c024d6.png)

Thanks!

**Comment by alexfedoseev** [comment] 2018-03-12 02:32
@jchavarri Sure, here's the log: [atom-reason-broken-pipe.log](https://github.com/freebroccolo/ocaml-language-server/files/1801221/atom-reason-broken-pipe.log)

During this log session error popped up 2 times:

1. after I saved on `2018-03-12 10:19:15.911`
2. after I saved on `2018-03-12 10:19:30.967`

**Comment by bobzhang** [comment] 2018-06-01 05:03
Hi all, I am going to introduce a push mode for bsb, so whenever `bsb` finished a job, it will send a message to the websocket client, let me know if it could help here
